### ISSUE TITLE
Manage buffs frame

### ISSUE THREAD

**Issue by Lugnaut** [leatrix/leatrix-plus-wrath#121]
I understand that the most recent update caused leatrix plus to not work if elvui already has control, but I'm unable to move the buff frames when i have them disabled in elvui.

**Comment by leatrix** [comment]
Please try the latest alpha (3.0.00.alpha.5 or later).
It includes the following changes:

- Manage buffs will be unavailable if Buffs > Disabled Blizzard is enabled.
- Manage focus will be unavailable if UnitFrames > Disabled Blizzard Frames > Focus is enabled.
- Show player chain will be unavailable if UnitFrames > Disabled Blizzard Frames > Player is enabled.
- Hide portrait numbers will be unavailable if UnitFrames > Disabled Blizzard Frames > Player is enabled.
- Class colored frames will be unavailable if UnitFrames > Disabled Blizzard Frames > Player, Target or Focus is enabled.

If you feel more changes are needed, let me know.

**Comment by Lugnaut** [comment]
Sorry if there was any misunderstanding, I lost functionality to manage buffs when Elvui isn't in control of them in TBC classic, after downloading the alpha version and attempting to use it in tbc folder it didn't appear to function at all.

**Comment by leatrix** [comment]
Ah, I see.  In that case, disable all addons except LTP.  It should work fine.  So enable other addons gradually until you find the addon causing the problem.  If you let me know what that addon is, I can advise you further.

The new alpha releases (version 3.x) are for Wrath only.  That's why CurseForge doesn't offer them for BCC.  For BCC, use the version that CurseForge offers (that should be 2.5.120).  When the pre-patch is live on Tuesday/Wednesday, CurseForge should update it to 3.x automatically.

**Comment by Lugnaut** [comment]
It continued to work directly after disabling Elvui first and only. I dont use elvui for buffs but hafter this last update of Leatrix plus on wednesday it removed the ability to use Leatrix to manage buffs even when elvui buffs are disabled and im not disabling blizzard buffs.

**Comment by leatrix** [comment]
It is fixed in the latest alpha but that's only for Wrath (pre-patch).  For BCC, keep using 2.5.119 until the pre-patch on Tuesday/Wednesday then update to the latest release (3.x) and it will work as per https://github.com/leatrix/leatrix-plus-wrath/issues/121#issuecomment-1229413451.
