### ISSUE TITLE
Buff Frame Vertical Spacing

### ISSUE THREAD

**Issue by da-rk** [leatrix/leatrix-plus-wrath#140]
Currently the buff spacing is a little TOO close together vertically, the remaining timer underneath the buffs when set to 150%+ overlap the buff below it making it hard to see the leftover duration of the buff above --

While writing this I can't currently provide an image but will provide an image soon,

Apologies if this was brought up by someone already, did a quick search and couldn't find another post

**Comment by da-rk** [comment]
Additionally forgot to mention, the bug is still present with all other addons disabled

**Comment by leatrix** [comment]
Many thanks for your report.  Please try 3.0.08.alpha.4 and it should work fine.  LTP doesn't interfere with the individual buff icon spacing.  The bug was actually caused by the new consolidated buffs icon not being scaled.

If you want to test this out solo, log into a character that is able to give themselves 3 or 4 buffs (such as a mage) then enter this command:

`/run BUFFS_PER_ROW = 2; BuffFrame_UpdateAllBuffAnchors();`

Only two buffs will now be shown per row so if you have 3 or 4 buffs, you will see two rows of buffs and you can now test out the scaling.

After you have finished testing, be sure to reload your UI with `/reload` to ensure that the command you entered is cleared from memory and won't cause any issues.

**Comment by da-rk** [comment]
Thanks for the swift fix, it does appear to be fixed in 3.0.08.alpha.4

![image](https://user-images.githubusercontent.com/65447446/190929501-38a5af78-4ada-4317-9f94-467f7b4c3ed4.png)

Thanks a lot, have a great evening!
