### ISSUE TITLE
Guild name appearing twice in tooltips

### ISSUE THREAD

**Issue by Calzeru** [leatrix/leatrix-plus-wrath#142]
Guild names appear in tooltips with the default Blizzard UI.
If I enable the "Enhance tooltip" option in Leatrix, guild names now appear twice.

Is it possible to remove the default blizzard guild name showing when using Leatrix's "Enhance tooltip" option?

**Comment by leatrix** [comment]
Leatrix Plus enhance tooltip only colors the guild name.  If you are seeing the guild name twice, disable all other addons.  It should work fine so enable other addons again gradually until you find the addon causing the guild name to appear twice.  You can then either disable that addon or let me know the addon name and your game locale so that I can advise you further.

**Comment by Calzeru** [comment]
Apologies, my mistake. It didn't cross my mind that it could be another addon because as far as I knew I had no other addons that has anything to do with the tooltip. Turns out the addon "LFG Bulletin Board" for some reason has a "Guild names in tooltip" option enabled by default. Not what I use the addon for at all...

Thanks for the response.
