### ISSUE TITLE
Chat class color issue

### ISSUE THREAD

**Issue by Angerreign** [leatrix/leatrix-plus-wrath#166]
Because of non-modular nature of addon, some fetaures cuase conflict with other addons. If you chance some settign about chat, it will override your other chat addon settings like BasicChatMods. Like if you change class color settings from LTP, it will override your BCM settings. Nothing you do from BCM will revert change you have done with LTP. If you disable chat class color from LTP, enableing it from BCM will not work.

I'm mostly using interface tweaks and loving it but things like this makes it really annoying to use LTP. Can we enable a chosen part of the addon but disable the rest ?

**Comment by leatrix** [comment]
> Can we enable a chosen part of the addon but disable the rest ?

That is the whole point of LTP.  It allows you to do exactly that.

LTP is fully modular.  Option code is typically only run if the option is enabled.  It's one of the best things about the addon.

If you use BCM, you should not be enabling 'Use class colors in chat' in LTP because BCM has its own class color setting (Player Names > Class Colors).

Don't enable options in LTP that already exist in other addons.

> If you disable chat class color from LTP, enableing it from BCM will not work.

I just tested this and it works fine for me.  I enabled 'Use class colors in chat' and I got class colors in chat.  I disabled 'Use class colors in chat' and I still got class colors in chat because it was enabled in BCM.  If I disable the BCM setting and the LTP setting, I do not get class colors in chat as expected.

**Comment by Angerreign** [comment]
The more you know... Thank you for your kind answer. 
> LTP is fully modular. Option code is typically only run if the option is enabled. It's one of the best things about the addon.
Perhaps I messed it up. Its good to know this.

I was able to enable Class Colors from blizzard chat settings. So its not about LTP or BCM but me doing things wrong.
Good days.

**Comment by leatrix** [comment]
The problem with Blizzard chat settings is that you need to enable a myriad of checkboxes across multiple menus just to enable class colors in chat.  The 'Use class colors in chat' setting in the latest release of LTP checks all those boxes for you so you don't have to worry about it.
