### ISSUE TITLE
Enhanced tooltip/buffs/minimap keeps getting disabled while using ElvUI (I have the modules disabled)

### ISSUE THREAD

**Issue by sandervspl** [leatrix/leatrix-plus-wrath#168]
As the title describes, I want to use the Leatrix minimap, tooltip, and buffs module while using ElvUI. Leatrix tells me to disable the modules in ElvUI, which I have done. This allows me to enable the Leatrix modules. However, every time I log out and log back in, it will randomly disable the Leatrix modules. I am on the latest ElvUI (v12.91) and Leatrix (v3.0.36) versions

**Comment by leatrix** [comment]
On login/reload, LTP checks to see if your ElvUI saved settings file has specific settings enabled.  If it does, it disables certain LTP options that are likely to conflict.

LTP saves its settings account-wide.  ElvUI saves its settings per character profile.  If you login to a character that uses an ElvUI profile with the modules above enabled, LTP is going to disable the settings account-wide.  To stop this from happening, you need to ensure that all of your character ElvUI profiles have the relevant ElvUI modules disabled.

If that is already the case, try to give me some steps so that I can to replicate the issue you are having.

**Comment by sandervspl** [comment]
@leatrix Ah, that makes total sense. I was switching between characters for trick or treat, and some of them had ElvUI enabled. I disabled it on all characters and my main character's Leatrix settings now remain as they should. Thanks!

**Comment by leatrix** [comment]
This should help.
> 3.0.38.alpha.1 - 20th October 2022
> - Having ElvUI installed will no longer uncheck conficting option checkboxes.  Conflicting option checkboxes will still be locked but they won't be unchecked.  So if a conflicting option checkbox was checked before installing ElvUI or before enabling a conflicting ElvUI module, it will still be checked after disabling ElvUI or disabling the conflicting ElvUI module.

**Comment by sandervspl** [comment]
@leatrix Awesome! Thanks!
