### ISSUE TITLE
Strange interaction between Leatrix Plus, Bartender4, and AceHook

### ISSUE THREAD

**Issue by nteetor** [leatrix/leatrix-plus-wrath#171]
The error is as follows,

```
34x Leatrix_Plus\Leatrix_Plus-3.0.37.lua:9777: Usage: HookScript(object, method, [handler]): 'object' - nil or table expected got string
[string "=[C]"]: ?
[string "@Bartender4\libs\AceHook-3.0\AceHook-3.0-9.lua"]:130: in function <...eBartender4\libs\AceHook-3.0\AceHook-3.0.lua:118>
[string "@Bartender4\libs\AceHook-3.0\AceHook-3.0-9.lua"]:367: in function `HookScript'
[string "@Leatrix_Plus\Leatrix_Plus-3.0.37.lua"]:9777: in function `HighlightTabs'
[string "@Leatrix_Plus\Leatrix_Plus-3.0.37.lua"]:9794: in function `?'
[string "@Leatrix_Plus\Leatrix_Plus-3.0.37.lua"]:12893: in function <Leatrix_Plus\Leatrix_Plus.lua:12367>

Locals:
(*temporary) = "Usage: HookScript(object, method, [handler]): 'object' - nil or table expected got string"
```

The error appears with and without Bartender4 enabled. I'm not sure what other information to provide up front. Please let me know what else I can provide to help.

**Comment by leatrix** [comment]
Disable all addons except LTP.  If the problem is solved, enable other addons gradually until you find the addon causing the problem.  You can then either disable that addon or tell me what that addon is so I can advise you further.

It looks to be some kind of conflict with Hide chat buttons ('Chat') so possibly caused by a chat addon.

**Comment by nteetor** [comment]
The error persists with all other addons disabled aside from BugSack and BugGrabber.

**Comment by nteetor** [comment]
The error comes from an interaction between the Glass addon and Leatrix

**Comment by leatrix** [comment]
When I tried to install Glass for Wrath of the Lich King Classic, there were errors with all other addons disabled.

When I checked the author's [GitHub page](https://github.com/mixxorz/Glass), it tells me that Glass is no longer being supported as the author has quit Wow.  So if that's the version you are using, you should stop using Glass.

For me to test Glass, provide me with a link to the addon that works in Wrath of the Lich King Classic (this ticket is for Wrath Classic so I'm assuming that's the game you are using).

On the author's CurseForge page, the author recommends disabling some LTP chat features that Glass replaces.  However, because the official version of Glass appears broken in Wrath of the Lich King Classic, it is preventing LTP from loading correctly and therefore disabling settings in LTP doesn't work either.  So for that version of Glass, you need to disable Glass in order to disable LTP features.

**Comment by leatrix** [comment]
So after commenting out lines 14 and 16 of Glass\constants.lua (`if WOW_PROJECT_ID == WOW_PROJECT_CLASSIC then` and `end`), Glass seemed to work correctly.  However, it does conflict with a few of the Leatrix Plus chat options.

To fix it, you need to disable Glass, reload and then disable the following LTP chat options:

- Use easy resizing
- Hide the combat log
- Hide chat buttons
- Unclamp chat frame
- Move editbox to top
- More font sizes
- Use class colors in chat
- Recent chat window

After you have disabled the above options and reloaded, you can enable Glass again and it should work fine.

But note that if you enable any of the above options and reload, they will conflict with Glass and prevent LTP from loading correctly.  So you will need to disable Glass in order to disable the options in LTP.

**Comment by leatrix** [comment]
Glass doesn't seem to work as it is but after commenting out lines 14 and 16 of Glass\constants.lua (if WOW_PROJECT_ID == WOW_PROJECT_CLASSIC then and end), Glass seemed to work correctly. However, it does conflict with a few of the Leatrix Plus chat options.

Because this issue with Glass has cropped up before, in Leatrix Plus 3.0.51.alpha.1, the following options will be locked out if you have Glass installed so you don't need to worry about conflicting options.

- Use easy resizing
- Hide the combat log
- Hide chat buttons
- Unclamp chat frame
- Move editbox to top
- More font sizes
- Disable chat fade
- Use class colors in chat
- Recent chat window

This should resolve the problem.

**Comment by nteetor** [comment]
I was all set to give up on Glass, so thank you for these fixes! I'll see how Glass interacts with the latest version of Leatrix.

**Comment by nteetor** [comment]
Seems to be working great, thank you again.
