### ISSUE TITLE
[WOLK] LTP 3.0.57 Questlog bug

### ISSUE THREAD

**Issue by zdinch** [leatrix/leatrix-plus-wrath#185]
Hi, since the last updates the questlog texture is wrong, everything else works correctly.

![ss+(2022-11-19+at+10 45 16)](https://user-images.githubusercontent.com/84704512/202845045-9d6776b9-9183-4d0c-9157-64e9cd493e9a.png)

Thanks for keeping the addon and sorry for my english!

**Comment by leatrix** [comment]
It works ok for me.  You appear to be using ElvUI and for me it looks fine in ElvUI too.

Restart your game client completely.  If that doesn't help, disable ElvUI to see if the quest log looks ok.  Let me know your findings.

**Comment by zdinch** [comment]
Hello! Thank you for answering so quickly, i don't use ElvUI, I use a texture pack to make the interface dark + LortUI.
I've tried to disable the addons and it doesn't work, before the last Letrix update it worked fine :(
Thank you!

**Comment by leatrix** [comment]
The texture pack is probably what is causing it.  It works fine with LortUI installed.  Link the texture pack that you are using.

**Comment by zdinch** [comment]
Hello! use this texture pack [DarkUI Wrath]https://www.curseforge.com/wow/addons/darkuiwrathl)

Ty!

**Comment by zdinch** [comment]
Hello! use this texture pack [https://www.curseforge.com/wow/addons/darkuiwrathl](url)
Ty!

**Comment by leatrix** [comment]
- Open Interface\AddOns\Lorti-UI-Classic\core\frames.lua with Notepad++ (or Notepad if you don't have Notepad++).
- Find `if IsAddOnLoaded("Leatrix_Plus")`.
- Change it to `if IsAddOnLoaded("Leatrix_Plus2")` (so all you are doing is adding a number `2` after the word `Plus`).
- Save the file and `/reload` your UI.  It should work now.
- Report the issue to LortUI so that the author can update the addon.  LTP used to contain a setting to make the quest log taller.  That setting had to be removed because of Blizzard's changes to the game code (yay, Blizzard!) but LortUI thinks the taller quest log is still being used.  That's all.

**Comment by zdinch** [comment]
Hi! now if it works correctly.
Thank you very much!
